### ISSUE TITLE
id crashes LibTerm

### ISSUE THREAD

**Issue by teor2345** [ColdGrub1384/LibTerm#10]
When I use the id command, LibTerm crashes.

Steps to reproduce:
1. Open LibTerm
2. Type "id" then return

Actual behaviour:

LibTerm exits immediately.

Expected behaviour:

id output appears in the shell window.

Diagnostic steps:

The following commands do not crash:
* id -h
* id foo
* id -F
* id (any other argument given by id -h)

The following commands do crash:
* id
* id 501
* id 0

Further information:

I am using LibTerm 2.0 on iOS 12.1 on an iPad Mini.

**Comment by ColdGrub1384** [comment]
Thank you! I will try to fix that

**Comment by ColdGrub1384** [comment]
Fixed by b2f4496
