### ISSUE TITLE
Would git be possible on LibTerm

### ISSUE THREAD

**Issue by Shock9616** [ColdGrub1384/LibTerm#12]
I am wondering if there are any plans to add git to LibTerm. Would it be added in an app update? Or would someone have to make a git command in python?

**Comment by ColdGrub1384** [comment]
It would be very difficult to compile. There is a library to do Git with Python: https://github.com/dulwich/dulwich. But the command itself should be rewrote.

**Comment by Shock9616** [comment]
Ok. Thanks I was just curious
