### ISSUE TITLE
Exiting python crashes LibTerm

### ISSUE THREAD

**Issue by teor2345** [ColdGrub1384/LibTerm#13]
When I exit the python command, LibTerm crashes.

Steps to reproduce:

1. Open LibTerm
2. Type "python" then return
3. Type "quit()" then return
OR
3. Type "import sys; sys.exit()" then return

Actual behaviour:

LibTerm exits immediately.

Expected behaviour:

python exits, but LibTerm does not.

Diagnostic steps:

The following commands do not crash:

The "Stop" autocompletion above the keyboard in LibTerm when python is open.

Further information:

I am using LibTerm 3.0.1 (3) on iOS 12.1 on an iPad Mini.

**Comment by ColdGrub1384** [comment]
Thanks! I will fix it soon.

**Comment by ColdGrub1384** [comment]
Don't update LibTerm until the next update: #14

**Comment by ColdGrub1384** [comment]
Fixed by 795454c57e80caa78de5145eb502737e900604b3
