### ISSUE TITLE
Python 3.7 doesn't work.

### ISSUE THREAD

**Issue by ColdGrub1384** [ColdGrub1384/LibTerm#14]
I made Python 3.7 an In App Purchase. But the purchase doesn't work. Also, people that downloaded the app when Python 3.7 was free should not have to purchase it. I submitted a new update fixing that.

**Comment by ColdGrub1384** [comment]
I think I found the solution

**Comment by ColdGrub1384** [comment]
You can update, the Python 3.7 In App Purchase is free for now.

**Comment by Shock9616** [comment]
I just tried to unlock python 3 with the in app purchase but it is giving me a product not found error. I am following the instructions and letting you know so that you can fix the bug.
![6e3f0814-8cf7-44ee-ac1e-e3219612126f](https://user-images.githubusercontent.com/28808006/50372029-7dba7a00-057b-11e9-982b-39da1ea82486.png)

**Comment by Shock9616** [comment]
Maybe it is taking longer for the fix to reach me. Updates sometimes take a bit longer to get to my region.

**Comment by ColdGrub1384** [comment]
I think it will take some time for the In App Purchase to be available, it happened to me with another app. I have put the In App Purchase to 0$ until I will fix all bugs. I submitted an update that should be available today that should unlock Python 3.7 for all users who downloaded the app before the 4.0. The problem is that only works on App Store versions because I have to check a receipt given by the App Store, so I can only check if that works when the app is on the App Store. But I think I found the problem. Apple said that In App Purchases can take up to 24 hours to be available. That’s not a bug of my app because if we try to purchase Python 3.7 from the App Store, it doesn’t work. And also the app will be rejected if the In App Purchase would not work. Sorry for all bugs 😓. When the purchase will be available, you can purchase it and it will be free. On the next update, it should be free for users who downloaded the app before the 4.0 and paid for other users.

**Comment by Shock9616** [comment]
Ok thanks for letting me know!

**Comment by ColdGrub1384** [comment]
The In App Purchase works now, it’s free for now.

**Comment by adbennet** [comment]
(1) I don't know if this is related to the in-app purchase, but I updated from 3.0.1 to 4.0.1, and opened LibTerm, I got a popup "Sign in to iTunes Store". It seems unnecessary, out of reflex I clicked cancel and LibTerm seems to work okay. If I kill the app and re-open, I get the popup again. If I switch away from the app and re-open, I do not get the popup.
(2) I successfully purchased python 3.7 for free. Notably, I did not get a popup, I got a different Apple sign-in dialog that I have seen many times before. The next time I opened LibTerm, I got the popup again. Killing/switching behaves the same as in my item-1, before the in-app purchase.
(3) I think your policy RE python2/3 is very well thought out. Kudos.

**Comment by ColdGrub1384** [comment]
That's I wanted to do: https://stackoverflow.com/a/39876448/7515957

> I am in the process of switching an app from paid to freemium so I also need the original application version.

**Comment by ColdGrub1384** [comment]
https://github.com/ColdGrub1384/LibTerm/commit/e8c63614eb5943f51ecd1579d1a78d9b3da0e26e#r31766340

**Comment by ColdGrub1384** [comment]
> App Store Connect Holiday Schedule: Dec 23–27
> Make sure your apps are up to date and ready for the holidays. New apps and app updates will not be accepted December 23 to 27 (Pacific Time), so any releases should be submitted, approved, and scheduled in advance. Other App Store Connect and developer account features will remain available.

I will request an expedited review

**Comment by ColdGrub1384** [comment]
All should work now.
