### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by alexjefferson** [ColdGrub1384/LibTerm#15]
import subprocess
...
subprocess.call('netsh interface ipv4 set interface ""Wireless Network" metric=1', shell=True)
Idk why. When i use the code on the top always force close the program.can any one help me?

**Comment by ColdGrub1384** [comment]
`subprocess`module is not yet supported. Also, `netsh` is a Windows command.

**Comment by alexjefferson** [comment]
Oh oke thx Mr Cold.
