### ISSUE TITLE
Python input() function causes EOF error

### ISSUE THREAD

**Issue by dullbananas** [ColdGrub1384/LibTerm#20]
The error occurs immediately when `input()` is called.

**Comment by dullbananas** [comment]
I want this fixed soon

**Comment by dullbananas** [comment]
I want getpass to work as well

**Comment by ColdGrub1384** [comment]
I cannot reproduce it. Does it happen everytime?

**Comment by dullbananas** [comment]
Yes. It happens when `input()` is called from a script in the scripts directory, but not in the interactive console.

**Comment by dullbananas** [comment]
Actually, it does work if I enter the interactive console then exit before running the script.

**Comment by dullbananas** [comment]
But some other issues occur even if input() works.

**Comment by ColdGrub1384** [comment]
Fixed by 152742beaf9bea1cc092d911e4831ddd87204cf9

**Comment by dullbananas** [comment]
yay
