### ISSUE TITLE
LibTerm pulled from AppStore?

### ISSUE THREAD

**Issue by sn3ksoftware** [ColdGrub1384/LibTerm#26]
Apparently, when I tried to access the LibTerm app here (in Singapore) within Apple’s appstore, there was no search results. Also, when the appstore link in Github is accessed, the App Store claims that the app does not exist in this region.
I hope that this app does not get pulled from the App Store like OpenTerm. It, as well as Libterm was a great app.

**Comment by dullbananas** [comment]
I can't find either and I'm in the United States. This is just saf

**Comment by dullbananas** [comment]
R.I.P. LibTerm

**Comment by sn3ksoftware** [comment]
Openterm was pulled from the App Store a loooong time ago, when it’s dev started working for Apple. But I would be worried if Libterm was really gone for good.

**Comment by Kevin-He-DVHS** [comment]
I also experienced the temporary unavailability on App Store, but the good news is that LibTerm is **up** again by now (7/23/2019)🎉.
You can try [the link on App Store](https://apps.apple.com/us/app/libterm/id1380911705?ls=1).

**Comment by dullbananas** [comment]
YES!!!!!! It's such a useful app and it would be terrible for it to disappear! 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by sn3ksoftware** [comment]
Thanks for letting me know @Kevin-He-DVHS. I’ll close this issue now because Libterm was put back on the App Store.
