### ISSUE TITLE
LibTerm crashing after new update

### ISSUE THREAD

**Issue by dullbananas** [ColdGrub1384/LibTerm#29]
I updated to LibTerm 5.0, and now it crashes whenever I open it.
![ezgif-1-e9ac56c2ffe1](https://user-images.githubusercontent.com/47706471/64900404-e84da180-d645-11e9-8a41-e8fab7e19b66.gif)

**Comment by Nojus297** [comment]
Same for me. 
Iphone 6, ios 12.3.1

**Comment by Nojus297** [comment]
Crash log file if thats helpfull:
[LibTerm-2019-09-14-125237.txt](https://github.com/ColdGrub1384/LibTerm/files/3612802/LibTerm-2019-09-14-125237.txt)

**Comment by dullbananas** [comment]
this is my crash report:
[LibTerm-2019-09-13-164100.txt](https://github.com/ColdGrub1384/LibTerm/files/3612832/LibTerm-2019-09-13-164100.txt)

**Comment by ColdGrub1384** [comment]
Thank you! That is happening on iOS 12. I fixed the crash and a new update is coming soon. Sorry guys.

**Comment by ColdGrub1384** [comment]
It's now fixed
