### ISSUE TITLE
Siri Shortcuts Action

### ISSUE THREAD

**Issue by dullbananas** [ColdGrub1384/LibTerm#34]
When I run commands through Shortcuts app, I can't access the normal Documents directory. When I set its current directory as ~, it goes to /private/var/mobile/Containers/Data/PluginKitPlugin/078ACFAA-F951-4B67-9AC1-C74FFD2C2DC3. It should instead go to /private/var/mobile/Containers/Data/Application/B666351D-5F34-4CE2-8A48-A2EF0991F819/Documents. I tried to manually type in that path for the cwd, but it says operation not permitted.

You should also add the ability to send data as stdin with this Shortcuts action, and you should also improve the action's description.

**Comment by ColdGrub1384** [comment]
I added a `$SHAREDDIR` environment variable which is the path of a directory shared between Siri Shortcuts and the app. This is now the default current directory for Siri Shortcuts

**Comment by dullbananas** [comment]
There should be a way to access this shared dir through the Files app
