### ISSUE TITLE
Can’t run any executables in /bin /sbin or ~/Documents

### ISSUE THREAD

**Issue by dernyn** [ColdGrub1384/LibTerm#47]
iOS app : 
Can’t run any executables in /bin /sbin or ~/Documents

**Comment by ColdGrub1384** [comment]
LibTerm cannot run executables. LLVM IR code can be ran with the `lli` command.

**Comment by dullbananas** [comment]
Because of the restrictions of iOS and iPadOS

**Comment by dernyn** [comment]
so you can use the 'package' command to install third party commands(are these not executables?), but you can't call the commands from pakages but not native iOS commands?

**Comment by dullbananas** [comment]
Commands installed via `package` are written in Python. Custom native executables can't be executed.

**Comment by dernyn** [comment]
thanks for the clarification.
