### ISSUE TITLE
Make python be able to be run as commands

### ISSUE THREAD

**Issue by A765-ALEX** [ColdGrub1384/LibTerm#84]
Add 2 folders in /Library/bin/: cbin (for c code) and pybin (for python scripts, they function like installed by package install) so users can make their own commands without having to submit a pull request to the command repository.
Run commands in cbin using lli, and commands in pybin using python3

**Comment by ink-splatters** [comment]
+1 why not allow installing packages via pip / pipx? It would be much more handy. Anyway, each universal approach would be great. For @A765-ALEX maybe as a workaround, custom GitHub repo would work by setting up DNS cloaking (DNSCloak app)

**Comment by A765-ALEX** [comment]
@ink-splatters You _can_ install packages via pip, you need to run `python3 -m pip install packagename`
Just wanted to say.

**Comment by vovkapoc** [comment]
> @ink-splatters You _can_ install packages via pip, you need to run `python3 -m pip install packagename`
> 
> Just wanted to say.

iPhone $ python3 -m pip install colorama
Defaulting to user installation because normal site-packages is not writeable
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama
ERROR: Could not install packages due to an OSError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Applicatio

**Comment by A765-ALEX** [comment]
> > @ink-splatters You _can_ install packages via pip, you need to run `python3 -m pip install packagename`
> > Just wanted to say.
> 
> iPhone $ python3 -m pip install colorama Defaulting to user installation because normal site-packages is not writeable Collecting colorama Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB) Installing collected packages: colorama ERROR: Could not install packages due to an OSError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Applicatio

Yeah, you should probably open your own thread instead of reviving mine from 2 yrs and 1 mo ago...
